<?php

declare (strict_types = 1);

namespace App\ListContrib;

use Laminas\Diactoros\Response\JsonResponse;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;
use App\ListContrib\Controller;

class ListContrib implements RequestHandlerInterface
{
    public function handle(ServerRequestInterface $request): ResponseInterface
    {

        $cuerpo = array(
            array(
                'nompro' => 1,
                'codcon' => 31,
                'razsoc' => 'APAIZTEGUI BARRIOS SOCORRO ALICIA',
                'condir' => 'CALLE EMILIO CAVENECIA Num.: 316 Kmt.: 0 Agr.: 0',
                'condis' => 'SAN ISIDRO',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1629.09,
                'mondos' => 0.00,
                'montre' => 24.3,
                'moncua' => 70.67,
                'moncin' => 1724.06
            ),
            array(
                'nompro' => 1,
                'codcon' => 66,
                'razsoc' => 'CAÑARI AYMA LUIS',
                'condir' => 'JR. TASSO (EX CA.) Num.: 278 Mza.: L-9 Lot.: 15 Kmt.: 0 Agr.: 0 SAN BORJA',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 2523.96,
                'mondos' => 0.00,
                'montre' => 37.65,
                'moncua' => 109.49,
                'moncin' => 2671.1
            ),
            array(
                'nompro' => 1,
                'codcon' => 72,
                'razsoc' => 'RAFFO RAFFO FRANCO',
                'condir' => 'CALLE LAS FRESIAS URB. CAMACHO Num.: 215-219 Kmt.: 0 Cap.: 000343351 Agr.: 5',
                'condis' => 'LA MOLINA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1602.87,
                'mondos' => 0.00,
                'montre' => 71.73,
                'moncua' => 31.15,
                'moncin' => 1705.75
            ),
            array(
                'nompro' => 1,
                'codcon' => 156,
                'razsoc' => 'INMOBILIARIA  LURIAMA S.A.',
                'condir' => 'CALLE GADDI TADEO Num.: 174 Mza.: P-9 Lot.: 11 Kmt.: 0 Agr.: 0 Sec.: 06 URBANIZACION SAN BORJA SUR',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1872.18,
                'mondos' => 0.00,
                'montre' => 27.93,
                'moncua' => 81.21,
                'moncin' => 1981.32
            ),
            array(
                'nompro' => 1,
                'codcon' => 191,
                'razsoc' => 'SABA KHALOUCY ISA',
                'condir' => 'AV. DE LAS ARTES NORTE Num.: 1485 Mza.: F-2 Lot.: 13 Kmt.: 0 Agr.: 0 SAN BORJA',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 2481.51,
                'mondos' => 0.00,
                'montre' => 37.02,
                'moncua' => 107.64,
                'moncin' => 2626.17
            ),
            array(
                'nompro' => 1,
                'codcon' => 284,
                'razsoc' => 'PEREZ ORDOÑEZ ROSALINO EFRAIN',
                'condir' => 'CALLE PREISING Num.: 160-162 Kmt.: 0 Agr.: 0 SAN BORJA SUR',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1412.66,
                'mondos' => 0.00,
                'montre' => 63.22,
                'moncua' => 27.45,
                'moncin' => 1503.33
            ),
            array(
                'nompro' => 1,
                'codcon' => 299,
                'razsoc' => 'SILVA CUENTAS ANTONINO EGO',
                'condir' => 'CALLE HASSINGER JOHN Num.: 149 Mza.: I17 Lot.: 28 Kmt.: 0 Agr.: 0 SAN BORJA',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1040.32,
                'mondos' => 0.00,
                'montre' => 23.28,
                'moncua' => 34.14,
                'moncin' => 1097.74
            ),
            array(
                'nompro' => 1,
                'codcon' => 595,
                'razsoc' => 'DEL SOLAR VELASQUEZ MARTHA M.',
                'condir' => 'JR. DA VINCI, LEONARDO Num.: 312-314 Kmt.: 0 Agr.: 0 SAN BORJA',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 954.69,
                'mondos' => 0.00,
                'montre' => 14.24,
                'moncua' => 41.41,
                'moncin' => 1010.34
            ),
            array(
                'nompro' => 1,
                'codcon' => 716,
                'razsoc' => 'GUTIERREZ ESTRADA MARIA ALICIA',
                'condir' => '',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 948.81,
                'mondos' => 0.00,
                'montre' => 14.15,
                'moncua' => 41.16,
                'moncin' => 1004.12
            ),
            array(
                'nompro' => 1,
                'codcon' => 735,
                'razsoc' => 'VALENZUELA VIZCARRA JOSE ALFONSO',
                'condir' => 'JR. MONTELLANOS ALBERTO Num.: 170 Kmt.: 0 Agr.: 0',
                'condis' => 'LA VICTORIA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1857.06,
                'mondos' => 0.00,
                'montre' => 27.7,
                'moncua' => 80.56,
                'moncin' => 1965.32
            ),
            array(
                'nompro' => 1,
                'codcon' => 737,
                'razsoc' => 'SANEZ ARAMBURU NATALIO ELIAS',
                'condir' => '',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1392.15,
                'mondos' => 0.00,
                'montre' => 20.77,
                'moncua' => 60.39,
                'moncin' => 1473.31
            ),
            array(
                'nompro' => 1,
                'codcon' => 808,
                'razsoc' => 'CORZO MANRIQUE MARINA',
                'condir' => 'JR. ARTEAGA CRNL. NICANOR ( EX CALLE 22) Num.: 793 Mza.: N-3 Lot.: 13 Kmt.: 0 Agr.: 0 URBANIZACION JACARANDA',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1439.94,
                'mondos' => 0.00,
                'montre' => 21.48,
                'moncua' => 62.47,
                'moncin' => 1523.89
            ),
            array(
                'nompro' => 1,
                'codcon' => 834,
                'razsoc' => 'BARAHONA BARONA MARCELINO',
                'condir' => '',
                'condis' => 'LIMA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1902.39,
                'mondos' => 0.00,
                'montre' => 28.38,
                'moncua' => 82.52,
                'moncin' => 2013.29
            ),
            array(
                'nompro' => 1,
                'codcon' => 872,
                'razsoc' => 'RUIZ ULLOA LUIS ENRIQUE',
                'condir' => '',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 987.3,
                'mondos' => 0.00,
                'montre' => 14.73,
                'moncua' => 42.83,
                'moncin' => 1044.86
            ),
            array(
                'nompro' => 1,
                'codcon' => 874,
                'razsoc' => 'RUIZ ULLOA GLADYS MERCEDES',
                'condir' => 'JR. BEETHOVEN Num.: 304 Mza.: J13 Lot.: 16 Kmt.: 0 Agr.: 0 Sec.: 07 URBANIZACION SAN BORJA SUR',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1574.91,
                'mondos' => 0.00,
                'montre' => 23.49,
                'moncua' => 68.31,
                'moncin' => 1666.71
            ),
            array(
                'nompro' => 1,
                'codcon' => 1259,
                'razsoc' => 'DELGADO ROSAS EVA ROSARIO',
                'condir' => 'JR. 24(EX CA.24) Num.: 393 Mza.: L-5 Lot.: 05 Kmt.: 0 Agr.: 0 URBANIZACION MARISCAL CASTILLA',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1063.83,
                'mondos' => 0.00,
                'montre' => 15.87,
                'moncua' => 46.14,
                'moncin' => 1125.84
            ),
            array(
                'nompro' => 1,
                'codcon' => 1373,
                'razsoc' => 'MONTOYA CRUZ DELFIN WASHINGTON',
                'condir' => 'AV. AVIACION Num.: 3461 Mza.: B Lot.: 01 Kmt.: 0 Agr.: 10 URBANIZACION LAS CAMELIAS DE SAN BORJA',
                'condis' => 'SAN BORJA',
                'codpre' => '',
                'dirpre' => '',
                'anoges' => 2021,
                'tiparb' => 'Imp.Pre.',
                'monuno' => 1132.68,
                'mondos' => 0.00,
                'montre' => 16.90,
                'moncua' => 49.13,
                'moncin' => 1198.71
            ),
            array(
                'nompro' => 2,
                'codcon' => 31,
                'razsoc' => 'APAIZTEGUI BARRIOS SOCORRO ALICIA',
                'condir' => 'CALLE EMILIO CAVENECIA Num.: 316 Kmt.: 0 Agr.: 0',
                'condis' => 'SAN ISIDRO',
                'codpre' => 4529,
                'dirpre' => 'JR. GOZZOLI (SUR) Num.: 254 Mza.: L-11 Lot.: 06 Kmt.: 8 Nu1.: 8C',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1216.17,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 52.42,
                'moncin' => 1268.59
            ),
            array(
                'nompro' => 2,
                'codcon' => 63,
                'razsoc' => 'ORBEGOSO VELEZMORO MARIA MARGARITA',
                'condir' => '',
                'condis' => 'SAN BORJA',
                'codpre' => 1090,
                'dirpre' => 'AV. AVIACION Num.: 2589 Dpt.: 01 Mza.: F4 Lot.: 13 Kmt.: 3 Nu1.: 3C',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1077.57,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 46.44,
                'moncin' => 1124.01
            ),
            array(
                'nompro' => 2,
                'codcon' => 66,
                'razsoc' => 'CAÑARI AYMA LUIS',
                'condir' => 'JR. TASSO (EX CA.) Num.: 278 Mza.: L-9 Lot.: 15 Kmt.: 0 Agr.: 0 SAN BORJA',
                'condis' => 'SAN BORJA',
                'codpre' => 2219,
                'dirpre' => 'JR. TASSO (EX CA.) Num.: 278 Mza.: L-9 Lot.: 15 Kmt.: 6 Nu1.: 6B',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1767.96,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 76.2,
                'moncin' => 1844.16
            ),
            array(
                'nompro' => 2,
                'codcon' => 155,
                'razsoc' => 'ECHEGARAY ABRILL EDGARD RENATO',
                'condir' => 'JR. DOMINGUEZ Num.: 463 Mza.: L-6 Lot.: 10 Kmt.: 0 Agr.: 0 SAN BORJA V ETAPA',
                'condis' => 'SAN BORJA',
                'codpre' => 2093,
                'dirpre' => 'JR. DOMINGUEZ Num.: 463 Mza.: L6 Lot.: 10 Kmt.: 4 Nu1.: 4A',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1140.84,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 49.17,
                'moncin' => 1190.01
            ),
            array(
                'nompro' => 2,
                'codcon' => 182,
                'razsoc' => 'VELARDE MANGO ALEJANDRINA',
                'condir' => 'JR. SINCHI ROCA Num.: 1591 Kmt.: 0 Agr.: 0',
                'condis' => 'JESUS MARIA',
                'codpre' => 9833,
                'dirpre' => 'AV. SAN LUIS Num.: 2157 Mza.: C6 Lot.: 07 Kmt.: 4 Nu1.: 4A',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1660.86,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 71.59,
                'moncin' => 1732.45
            ),
            array(
                'nompro' => 2,
                'codcon' => 191,
                'razsoc' => 'SABA KHALOUCY ISA',
                'condir' => 'AV. DE LAS ARTES NORTE Num.: 1485 Mza.: F-2 Lot.: 13 Kmt.: 0 Agr.: 0 SAN BORJA',
                'condis' => 'SAN BORJA',
                'codpre' => 8538,
                'dirpre' => 'AV. DE LAS ARTES NORTE Num.: 1485 Mza.: C7 Lot.: 03 Kmt.: 4 Nu1.: 4B',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1047.24,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 45.14,
                'moncin' => 1092.38
            ),
            array(
                'nompro' => 2,
                'codcon' => 207,
                'razsoc' => 'FUNDACION IGNACIA RODULFO VDA. DE CANEVARO',
                'condir' => '',
                'condis' => 'LIMA',
                'codpre' => 17228,
                'dirpre' => 'AV. JAVIER PRADO ESTE Num.: 3192 Int.: LOC.2 Mza.: A Lot.: 1 Kmt.: 4 Nu1.: 4A',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1574.1,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 67.84,
                'moncin' => 1641.94
            ),
            array(
                'nompro' => 2,
                'codcon' => 304,
                'razsoc' => 'INMOB. GRUPO DELTA S.A.',
                'condir' => 'AV. TOMAS ALVA EDISON Num.: 224 Kmt.: 0',
                'condis' => 'ATE',
                'codpre' => 11779,
                'dirpre' => 'JR. ANDREA DEL SARTO Num.: 121 Mza.: N-15 Lot.: 01 Kmt.: 7 Nu1.: 7A',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 968.67,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 41.76,
                'moncin' => 1010.43
            ),
            array(
                'nompro' => 2,
                'codcon' => 311,
                'razsoc' => 'CHU LAU LUIS Y SRA.',
                'condir' => 'AV. SAN LUIS Num.: 1966-A Mza.: A-3 Lot.: 3 Kmt.: 0 Agr.: 0 SAN BORJA',
                'condis' => 'SAN BORJA',
                'codpre' => 14438,
                'dirpre' => 'AV. SAN LUIS Num.: 1966 Dpt.: A Mza.: A3 Lot.: 24 Kmt.: 3 Nu1.: 3B',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1099.53,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 47.39,
                'moncin' => 1146.92
            ),
            array(
                'nompro' => 2,
                'codcon' => 361,
                'razsoc' => 'DE OLAZAVAL TEJADA LUIS ERNESTO',
                'condir' => 'CALLE ROSSETI DANTE (EX CA. 1 AMP. SAN BORJA) Num.: 111-115 Mza.: D Lot.: 10 Kmt.: 0 Cap.: 10005256 Agr.: 10 Sec.: 07 URBANIZACION SAN BORJA - AMPLIACION',
                'condis' => 'SAN BORJA',
                'codpre' => 3211,
                'dirpre' => 'AV. SAN BORJA SUR Num.: 594 Mza.: E11 Lot.: 03 Kmt.: 8 Nu1.: 8B URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1527.96,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 28.42,
                'moncin' => 1556.38
            ),
            array(
                'nompro' => 2,
                'codcon' => 379,
                'razsoc' => 'CAVAGNARO GARDELLA FEDERICO',
                'condir' => 'AV. ARICA PROLONG. Num.: 281 Kmt.: 0 Cap.: 08209187 Agr.: 10',
                'condis' => 'BREÑA',
                'codpre' => 65741,
                'dirpre' => 'JR. TASSO (EX CA.) Num.: 101 Mza.: D-2 Lot.: 12-1 Kmt.: 3 URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 4218.75,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 181.83,
                'moncin' => 4400.58
            ),
            array(
                'nompro' => 2,
                'codcon' => 380,
                'razsoc' => 'ALVAREZ GARCIA DE CAVAGNARO ESTELA',
                'condir' => '',
                'condis' => 'SAN BORJA',
                'codpre' => 65680,
                'dirpre' => 'CALLE DE LAS LETRAS Num.: 180 Int.: TDA. Dpt.: 6-7 Mza.: B Lot.: 06 Kmt.: 1 CONJUNTO HABITACIONAL',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1057.05,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 45.56,
                'moncin' => 1102.61
            ),
            array(
                'nompro' => 2,
                'codcon' => 595,
                'razsoc' => 'DEL SOLAR VELASQUEZ MARTHA M.',
                'condir' => 'JR. DA VINCI, LEONARDO Num.: 312-314 Kmt.: 0 Agr.: 0 SAN BORJA',
                'condis' => 'SAN BORJA',
                'codpre' => 3038,
                'dirpre' => 'JR. DA VINCI, LEONARDO Num.: 314 Mza.: G-4 Lot.: 29 Kmt.: 3 Nu1.: 3C', 'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1234.89,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 53.23,
                'moncin' => 1288.12
            ),
            array(
                'nompro' => 2,
                'codcon' => 649,
                'razsoc' => 'CARRANZA ZAVALA VICTOR ALBERTO',
                'condir' => 'AV. CANADA Num.: 3272 Mza.: M-4 Lot.: 12 Kmt.: 0 Agr.: 0 URBANIZACION JACARANDA',
                'condis' => 'SAN BORJA',
                'codpre' => 14283,
                'dirpre' => 'AV. CANADA Num.: 3274 Mza.: M4 Lot.: 12 Kmt.: 2 Nu1.: 2A URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1332.72,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 57.43,
                'moncin' => 1390.15
            ),
            array(
                'nompro' => 2,
                'codcon' => 735,
                'razsoc' => 'VALENZUELA VIZCARRA JOSE ALFONSO',
                'condir' => 'JR. MONTELLANOS ALBERTO Num.: 170 Kmt.: 0 Agr.: 0',
                'condis' => 'LA VICTORIA',
                'codpre' => 4524,
                'dirpre' => 'AV. DE LA ROSA TORO AGUSTIN Num.: 1296 Mza.: E5 Lot.: 01 Kmt.: 2 Nu1.: 2A',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 4503.96,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 194.12,
                'moncin' => 4698.08
            ),
            array(
                'nompro' => 2,
                'codcon' => 737,
                'razsoc' => 'SANEZ ARAMBURU NATALIO ELIAS',
                'condir' => '',
                'condis' => 'SAN BORJA',
                'codpre' => 70151,
                'dirpre' => 'AV. DE LAS ARTES NORTE Num.: 1297 Int.: U.I.1 Mza.: A5 Lot.: 01 Kmt.: 4 URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1537.56,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 66.27,
                'moncin' => 1603.83
            ),
            array(
                'nompro' => 2,
                'codcon' => 778,
                'razsoc' => 'LONGA MUÑOZ ABSALON LEONIDAS',
                'condir' => 'CALLE VARELA MARCELINI Num.: 118 Kmt.: 0 Agr.: 0',
                'condis' => 'LA VICTORIA',
                'codpre' => 1832,
                'dirpre' => 'AV. AVIACION Num.: 3305 Mza.: G2 Lot.: 32 Kmt.: 9 Nu1.: 9A URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 2306.34,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 99.41,
                'moncin' => 2405.75
            ),
            array(
                'nompro' => 2,
                'codcon' => 808,
                'razsoc' => 'CORZO MANRIQUE MARINA',
                'condir' => 'JR. ARTEAGA CRNL. NICANOR ( EX CALLE 22) Num.: 793 Mza.: N-3 Lot.: 13 Kmt.: 0 Agr.: 0 URBANIZACION JACARANDA',
                'condis' => 'SAN BORJA',
                'codpre' => 2687,
                'dirpre' => 'JR. ARTEAGA CRNL. NICANOR ( EX CALLE 22) Num.: 793 Mza.: N3 Lot.: 13 Kmt.: 2 Nu1.: 2B',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1276.56,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 55.02,
                'moncin' => 1331.58
            ),
            array(
                'nompro' => 2,
                'codcon' => 834,
                'razsoc' => 'BARAHONA BARONA MARCELINO',
                'condir' => '',
                'condis' => 'LIMA',
                'codpre' => 1318,
                'dirpre' => 'AV. AVIACION Num.: 2945 Mza.: B13 Lot.: 23 Kmt.: 7 Nu1.: 7B',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1987.11,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 85.64,
                'moncin' => 2072.75
            ),
            array(
                'nompro' => 2,
                'codcon' => 931,
                'razsoc' => 'INMOBILIARIA Y CONSTRUCTORA REL S.A.C.',
                'condir' => 'AV. SAN BORJA SUR Num.: 417 Mza.: K10 Lot.: 31 Kmt.: 0 Agr.: 0 Sec.: 06 URBANIZACION SAN BORJA SUR',
                'condis' => 'SAN BORJA',
                'codpre' => 88514,
                'dirpre' => 'AV. SAN BORJA SUR Num.: 417 Mza.: K10 Lot.: 31 Kmt.: 6 URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1694.16,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 73.01,
                'moncin' => 1767.17
            ),
            array(
                'nompro' => 2,
                'codcon' => 1040,
                'razsoc' => 'QUIROZ FRANCKOWIAK STEPHEN THOMAS',
                'condir' => 'AV. ROCA Y BOLOÑA Num.: 910 Kmt.: 0 Agr.: 0',
                'condis' => 'MIRAFLORES',
                'codpre' => 58641,
                'dirpre' => 'AV. GUARDIA CIVIL (EX. AV.DEL AIRE) Num.: 313 Mza.: A3 Lot.: 1-2 Kmt.: 3 URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 2250.81,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 97.01,
                'moncin' => 2347.82
            ),
            array(
                'nompro' => 2,
                'codcon' => 1040,
                'razsoc' => 'QUIROZ FRANCKOWIAK STEPHEN THOMAS',
                'condir' => 'AV. ROCA Y BOLOÑA Num.: 910 Kmt.: 0 Agr.: 0',
                'condis' => 'MIRAFLORES',
                'codpre' => 58642,
                'dirpre' => 'AV. GUARDIA CIVIL (EX. AV.DEL AIRE) Num.: 309 Mza.: A3 Lot.: 1-2 Kmt.: 3 URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1974.06,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 85.08,
                'moncin' => 2059.14
            ),
            array(
                'nompro' => 2,
                'codcon' => 1137,
                'razsoc' => 'MONTESINOS ROSASCO ADRIANA',
                'condir' => '',
                'condis' => 'MIRAFLORES',
                'codpre' => 54910,
                'dirpre' => 'AV. JAVIER PRADO ESTE Num.: 1804 Int.: B Mza.: A-1 Lot.: 04 Kmt.: 3 URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1224.81,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 52.78,
                'moncin' => 1277.59
            ),
            array(
                'nompro' => 2,
                'codcon' => 1142,
                'razsoc' => 'QUIROZ FRANCKOWIAK ANNETTE MARIE',
                'condir' => 'AV. ROCA Y BOLOÑA Num.: 910 Kmt.: 0 Agr.: 0',
                'condis' => 'MIRAFLORES',
                'codpre' => 94,
                'dirpre' => 'AV. GUARDIA CIVIL (EX. AV.DEL AIRE) Num.: 315 Mza.: A3 Lot.: 1-2 Kmt.: 3 Nu1.: 3A URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 3984.30,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 171.72, 
                'moncin' => 4156.02
            ),
            array(
                'nompro' => 2,
                'codcon' => 1142,
                'razsoc' => 'QUIROZ FRANCKOWIAK ANNETTE MARIE',
                'condir' => 'AV. ROCA Y BOLOÑA Num.: 910 Kmt.: 0 Agr.: 0',
                'condis' => 'MIRAFLORES',
                'codpre' => 58641,
                'dirpre' => 'AV. GUARDIA CIVIL (EX. AV.DEL AIRE) Num.: 313 Mza.: A3 Lot.: 1-2 Kmt.: 3 URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1265.94,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 54.57,
                'moncin' => 1320.51
            ),
            array(
                'nompro' => 2,
                'codcon' => 1142,
                'razsoc' => 'QUIROZ FRANCKOWIAK ANNETTE MARIE',
                'condir' => 'AV. ROCA Y BOLOÑA Num.: 910 Kmt.: 0 Agr.: 0',
                'condis' => 'MIRAFLORES',
                'codpre' => 58642,
                'dirpre' => 'AV. GUARDIA CIVIL (EX. AV.DEL AIRE) Num.: 309 Mza.: A3 Lot.: 1-2 Kmt.: 3 URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1110.33,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 47.85,
                'moncin' => 1158.18
            ),
            array(
                'nompro' => 2,
                'codcon' => 1234,
                'razsoc' => 'CASTRO HUAMAN MARIO CESAR',
                'condir' => 'JR. MARAÑON GREGORIO ( EX CA.) Num.: 105 Mza.: S11 Lot.: 01 Kmt.: 0 Cap.: 09997753 Agr.: 10 Eta.: III Sec.: B URBANIZACION SAN BORJA SUR',
                'condis' => 'SAN BORJA',
                'codpre' => 1694,
                'dirpre' => 'JR. MARAÑON GREGORIO ( EX CA.) Num.: 105 Mza.: S11 Lot.: 01 Kmt.: 8 Nu1.: 8B URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1009.08,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 32.69,
                'moncin' => 1041.77
            ),
            array(
                'nompro' => 2,
                'codcon' => 1247,
                'razsoc' => 'LOPEZ ABARCA GLADYS ELVIRA',
                'condir' => 'JR. MATIER Num.: 360 Mza.: O13 Lot.: 04 Kmt.: 0 Agr.: 0 SAN BORJA SUR',
                'condis' => 'SAN BORJA',
                'codpre' => 9507,
                'dirpre' => 'JR. MATIER Num.: 300 Mza.: O-13 Lot.: 04 Kmt.: 7 Nu1.: 7B',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1105.29,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 47.63,
                'moncin' => 1152.92
            ),
            array(
                'nompro' => 2,
                'codcon' => 1259,
                'razsoc' => 'DELGADO ROSAS EVA ROSARIO',
                'condir' => 'JR. 24(EX CA.24) Num.: 393 Mza.: L-5 Lot.: 05 Kmt.: 0 Agr.: 0 URBANIZACION MARISCAL CASTILLA',
                'condis' => 'SAN BORJA',
                'codpre' => 3333,
                'dirpre' => 'JR. 24(EX CA.24) Num.: 393 Mza.: L-V Lot.: 05 Kmt.: 5 Nu1.: 5B URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1037.34,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 44.71,
                'moncin' => 1082.05
            ),
            array(
                'nompro' => 2,
                'codcon' => 1277,
                'razsoc' => 'INMOBILIARIA  MONACO S.A.',
                'condir' => 'CALLE HORACIO CACHAY Num.: 389 Kmt.: 0 Agr.: 0',
                'condis' => 'LA VICTORIA',
                'codpre' => 14333,
                'dirpre' => 'AV. AVIACION Num.: 2462 Int.: TDA.1 Mza.: A2 Lot.: 12 Kmt.: 3 Nu1.: 3A URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1060.56,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 34.22,
                'moncin' => 1094.78
            ),
            array(
                'nompro' => 2,
                'codcon' => 1336,
                'razsoc' => 'ROJAS HERNANDEZ PEDRO RAFAEL',
                'condir' => '',
                'condis' => 'SAN ISIDRO',
                'codpre' => 24536,
                'dirpre' => 'JR. SALVADOR DALI Num.: 109 Dpt.: 202 Mza.: E5 Lot.: 18 Kmt.: 4 Nu1.: 4A',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1481.58,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 63.86,
                'moncin' => 1545.44
            ),
            array(
                'nompro' => 2,
                'codcon' => 1351,
                'razsoc' => 'SOTELO JARA JESUS',
                'condir' => '',
                'condis' => 'SAN BORJA',
                'codpre' => 13779,
                'dirpre' => 'AV. SAN BORJA SUR Num.: 398 Dpt.: TD07 Mza.: B11 Lot.: 14 Kmt.: 8 Nu1.: 8A URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1175.31,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 50.66,
                'moncin' => 1225.97
            ),
            array(
                'nompro' => 2,
                'codcon' => 1373,
                'razsoc' => 'MONTOYA CRUZ DELFIN WASHINGTON',
                'condir' => 'AV. AVIACION Num.: 3461 Mza.: B Lot.: 01 Kmt.: 0 Agr.: 10 URBANIZACION LAS CAMELIAS DE SAN BORJA',
                'condis' => 'SAN BORJA',
                'codpre' => 762,
                'dirpre' => 'AV. AVIACION Num.: 3465 Mza.: B Lot.: 01 Kmt.: 9 Nu1.: 9A URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1128.15,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 48.62,
                'moncin' => 1176.77
            ),
            array(
                'nompro' => 2,
                'codcon' => 1373,
                'razsoc' => 'MONTOYA CRUZ DELFIN WASHINGTON',
                'condir' => 'AV. AVIACION Num.: 3461 Mza.: B Lot.: 01 Kmt.: 0 Agr.: 10 URBANIZACION LAS CAMELIAS DE SAN BORJA',
                'condis' => 'SAN BORJA',
                'codpre' => 13710,
                'dirpre' => 'AV. AVIACION Num.: 3463 Mza.: B Lot.: 01 Kmt.: 9 Nu1.: 9A URBANIZACION',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1122.12,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 48.37,
                'moncin' => 1170.49
            ),
            array(
                'nompro' => 2,
                'codcon' => 1562,
                'razsoc' => 'KHOURY ZARZAR LUIS MIGUEL',
                'condir' => '',
                'condis' => 'SAN BORJA',
                'codpre' => 639,
                'dirpre' => 'JR. BRONZINO Num.: 199 Mza.: D5 Lot.: 20 Kmt.: 4 Nu1.: 4A',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1214.46,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 52.34,
                'moncin' => 1266.8
            ),
            array(
                'nompro' => 2,
                'codcon' => 1562,
                'razsoc' => 'KHOURY ZARZAR LUIS MIGUEL',
                'condir' => '',
                'condis' => 'SAN BORJA',
                'codpre' => 14539,
                'dirpre' => 'JR. BRONZINO Num.: 167 Mza.: D5 Lot.: 20 Kmt.: 4 Nu1.: 4A',
                'anoges' => 2021,
                'tiparb' => 'Arb. Mun.',
                'monuno' => 1024.56,
                'mondos' => 0.00,
                'montre' => 0.00,
                'moncua' => 44.16,
                'moncin' => 1068.72
            )

        );
        return new JsonResponse($cuerpo);
    }
}